### PR TITLE
Add key length validation to several AES Ciphers.

### PR DESCRIPTION
**Pull request by tmciver**
Addresses #113 

Please give feedback if this work is not in keeping with the style of the cryptonite codebase.  I'm particularly interested in any thoughts concerning the proper location of the function `validateKeySize` since it is rather generic and should work with any `Cipher` so probably does not belong in `Crypto.Cipher.AES`.

### CODE REVIEW

**Comment by vincenthz** [comment]
Overall fine, but it might be simpler to just assume the key size per cipher (just like the above line) instead of jumping through an undefined and a generic function

**Comment by vincenthz** [comment]
Just going to merge it to make a new release, but I'll appreciate if you could address the comment in the future (no obligation, the code works, Thanks !)

**Comment by tmciver** [comment]
@vincenthz Cool.  Can you clarify what you'd like to have changed?  Do you mean perhaps having a function that takes the key size as a parameter and just hard-code that at the call site?

**Comment by vincenthz** [comment]
yes exactly a function taking the size directly. it's hardcoded above, so there's not too much problem here, ideally something to avoid, but here it's pretty harmless

**Pull request merged**
