### PR TITLE
Fixed hash truncation bug in DSA

### PR DESCRIPTION
**Pull request by crockeea**
This fixes the hash truncation bug from #264. I added KATs from RFC 6979 to verify correctness.

DSA should also now handle `q` whose bit length is not a multiple of 8. I was unable to find any KATs for parameters of this type, so this code is untested.

### CODE REVIEW

**Comment by ocheron** [comment]
Code is correct and the test vectors are definitely wanted.

One concern though: what you add is really similar to function `tHash` in Crypto.PubKey.ECC.ECDSA.
So one may also move `tHash` somewhere like Crypto.PubKey.Internal, and use this for both DSA and ECDSA. Would you like trying this?

Also unclear to me why you kept the FIXME.

**Comment by crockeea** [comment]
@ocheron Thanks for the review. I'll fix your suggestions soon.

**Comment by crockeea** [comment]
Should be fixed now.

**Review by ocheron — APPROVED** [review]
Yes, looking good. Thanks.

**Pull request merged**
