### PR TITLE
Example of symmetric encryption in documentation.

### PR DESCRIPTION
**Pull request by yogsototh**
It took me way too long and to search in you tests to discover how to encrypt a file using a key.
So I believe it would be a good idea to just provide some example of usage.

I believe `ctrCombine` with AES256 should be good enough for most usage of symmetric encryption.

So I simply gave an example. I put the example in a `Crypto.Tutorial` as it is done for the `Turtle` library which is praised for its documentation.

### CODE REVIEW

**Comment by vincenthz** [comment]
I think it's a great idea, but is there a way we could typecheck / execute the tutorial code ? I would like to have it as part of the automated testing to make sure we don't ship tutorial that are useless

**Comment by yogsototh** [comment]
Yes, trying to find a solution I discovered the `doctest` package:

https://github.com/sol/doctest#readme

it could be used simply like this:

https://github.com/Gabriel439/Haskell-Turtle-Library/blob/master/test/Main.hs

So you could provide testing on the documentation.

**Comment by tekul** [comment]
I use doctest in one of my projects and it works pretty well. It can also be added as a separate test suite in the cabal file.

I think it'd be a good idea to use a more realistic AES256 key in the example. Perhaps hex or base64 decode an actual random key of the correct size?

**Comment by vincenthz** [comment]
merged it now to start experimenting with `doctest`, but definitely further doc improvement will be good

**Pull request merged**
