### PR TITLE
Code maintenance and cleanup

### PR DESCRIPTION
**Pull request by crockeea**
Apply after #265. Fixes many warnings related to redundant constraints, unused imports, deriving `Typeable` instances, and others. The PR is large, but it primarily affects the import lists and `deriving` clauses. A few type signature constraints were removed.

Compiles without warnings using GHC 8.6.3 (Stack LTS-13.2) with 
```
cryptonite> stack test cryptonite --ghc-options -Weverything --ghc-options -fno-warn-missing-local-signatures --ghc-options -fno-warn-unsafe --ghc-options -fno-warn-implicit-prelude --ghc-options -fno-warn-missing-import-lists --ghc-options -fno-warn-safe --ghc-options -fno-warn-monomorphism-restriction --ghc-options -fno-warn-missing-export-lists --ghc-options -fno-warn-missing-exported-signatures --ghc-options -fno-warn-missing-signatures --ghc-options -fno-warn-missed-specializations --ghc-options -fno-warn-all-missed-specializations --ghc-options -fno-warn-incomplete-uni-patterns --ghc-options-fno-warn-orphans
```

Hiding `-Wincomplete-uni-patterns` because all cases look good to me in the main library code.

Remaining question: Why are there so many missed specializations (remove `-fno-warn-all-missed-specializations`), and what should be done about it?

### CODE REVIEW

**Comment by ocheron** [comment]
The changes are good but I'm unsure about removing class constraints on API.
For `ivAdd` it looks OK. For the following I would prefer to keep the constraints, as it is useful for documentation or consistency with other functions:
- Crypto/KDF/PBKDF2.hs
- Crypto/OTP.hs
- Crypto/Random/Types.hs
- tests/BlockCipher.hs

Regarding -fwarn-all-missed-specializations it's about choosing between NOINLINE (code size) or INLINABLE (possible speed). I think we can add INLINABLE to `i2ospOf` in Crypto.Number.Serialize.

**Comment by crockeea** [comment]
@ocheron Updated per your requests.

**Review by ocheron — APPROVED** [review]
Thanks a lot, I merge.

**Comment by ocheron** [comment]
After this work I also removed `-fno-warn-unused-imports` from the build.

**Pull request merged**
