### PR TITLE
More efficient digestFromByteString

### PR DESCRIPTION
**Pull request by avieth**
By avoiding `ByteArray.convert`, `digestFromByteString` is much more efficient. 391 bytes allocated versus 1917. 135 nanoseconds versus 1.286 microseconds.

### CODE REVIEW

**Comment by avieth** [comment]
If this is merged I recommend squashing it first.

**Comment by vincenthz** [comment]
I could merge what's already there if you remove the latest commit; it's best to start the other thing as another PR

**Comment by avieth** [comment]
> I could merge what's already there if you remove the latest commit; it's best to start the other thing as another PR


Done

**Comment by vincenthz** [comment]
Thanks !

**Pull request merged**
