### PR TITLE
Add `hmacLazy` for lazy `ByteString`s

### LINKED ISSUE #220: Provide HMAC for Lazy Bytestrings
It would be nice to provide `hmacLazy`, so I can avoid repeated invocations of `concat` 🙂 

I think it will be something like (assuming `LBS` import):

```haskell
hmacLazy :: (ByteArrayAccess key, HashAlgorithm a) => key -> LBS.ByteString -> HMAC a
hmacLazy key lbs = finalize (foldl' update (initialize key) (LBS.toChunks lbs))
```

### PR DESCRIPTION
**Pull request by Porges**
Modeled off `hashLazy`.

Fixes #220

### CODE REVIEW

**Comment by ocheron** [comment]
Uppercase L looks nice but in the end I think lowercase is better: `hmaclazy` is the name used in packages forked from cryptohash.

**Comment by Porges** [comment]
@ocheron I named it to match the existing `hashLazy` in this library.

**Comment by ocheron** [comment]
Yes but it's `hashlazy` we already have. Otherwise I wouldn't hesitate 1 sec.

**Comment by vincenthz** [comment]
at this time, I regards `hashlazy` a bit as a historical mistake. so maybe we could unify to hashLazy/hmacLazy ? (with a soft deprecation, then hard deprecation, then removal over a long period of time)

**Comment by Porges** [comment]
Is there anything I need to do to bump this along?

**Comment by Porges** [comment]
@vincenthz is there any chance of accepting this, or should I close it off? (I'm cleaning up my old PRs)

**Comment by vincenthz** [comment]
yup, time to merge this ... it has been reviewed for long enough :p

**Comment by Porges** [comment]
@vincenthz thanks!

**Pull request merged**
